name: Sync To Gitee

on: [push, delete, create]

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      # - name: Use Node.js 16.x
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: "16.x"
      # - name: Cache NPM dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: node_modules
      #     key: ${{ runner.OS }}-npm-cache
      #     restore-keys: |
      #       ${{ runner.OS }}-npm-cache

      # # 上面是配置环境 下面开始正常 npm 流程
      # - name: Install Dependencies
      #   run: npm install --registry=https://registry.npm.taobao.org

      # # 可选
      # # 把在 plugin 目录下的插件拷贝到 node_modules 中，否则会构建失败
      # # - name: Install plugin
      # #  run: cp -rf plugins/hexo-filter-sequence/* node_modules/hexo-filter-sequence/

      # # deploy
      # - name: deploy
      #   run: npm run build

      # - name: Sync to Gitee
      #   uses: wearerequired/git-mirror-action@master
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      #   with:
      #     # 注意替换为你的 GitHub 源仓库地址
      #     source-repo: "git@github.com:DamnTime/blogs.git"
      #     # 注意替换为你的 Gitee 目标仓库地址
      #     destination-repo: "git@gitee.com:DamnTime/pluto.git"

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: DamnTime
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: DamnTime/pluto
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: master
